### ISSUE TITLE
Startpunkt Bild 

### ISSUE THREAD

**Issue by tmichelma** [mmmichelma/mmmichelma.github.io#12]
Toom Bild korrekt verlinken

**Comment by tmichelma** [comment]
Das Bild endet auf .tif und nicht auf .jpg

**Comment by mmmichelma** [comment]
Fertig!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
